using Microsoft.EntityFrameworkCore;
using MeineDeutscheLehrerin.Domain;
using MeineDeutscheLehrerin.Domain.Contracts;
using MeineDeutscheLehrerin.Domain.Entities;
using MeineDeutscheLehrerin.Infrastructure.Data;
using MeineDeutscheLehrerin.Infrastructure.Services;

namespace MeineDeutscheLehrerin.Api.Tools;

/// <summary>
/// CLI pipeline: enriches EXISTING vocabulary with a short usage note (what the word means and
/// when to use it) and a natural example, generated by the language-service (Claude via the
/// gateway). Idempotent — only words without a note are processed, so it can be run in batches
/// and resumed. Words are enriched per level so the examples are niveaugerecht.
/// Usage: dotnet run --project src/MeineDeutscheLehrerin.Api -- enrich-vocab [LEVEL|all] [limit]
/// </summary>
public static class VocabEnrichmentRunner
{
    private const int Batch = 25;

    public static async Task RunAsync(IServiceProvider services, string? levelCode, int limit)
    {
        using var scope = services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var lang = scope.ServiceProvider.GetRequiredService<ILanguageService>();

        IReadOnlyList<CefrLevel> levels;
        if (string.IsNullOrWhiteSpace(levelCode) || levelCode.Equals("all", StringComparison.OrdinalIgnoreCase))
            levels = new[] { CefrLevel.A1, CefrLevel.A2, CefrLevel.B1, CefrLevel.B2, CefrLevel.C1 };
        else if (Enum.TryParse<CefrLevel>(levelCode, ignoreCase: true, out var one))
            levels = new[] { one };
        else { Console.WriteLine($"Unknown level '{levelCode}'. Use A1, A2, B1, B2, C1 or all."); return; }

        int remaining = limit > 0 ? limit : int.MaxValue;
        int totalEnriched = 0;

        foreach (var code in levels)
        {
            if (remaining <= 0) break;
            var level = await db.Levels.FirstOrDefaultAsync(l => l.Code == code);
            if (level is null) { Console.WriteLine($"Level {code} is not seeded (skipped)."); continue; }

            var pending = await db.VocabularyItems
                .Where(v => v.LevelId == level.Id && (v.Note == null || v.Note == ""))
                .OrderBy(v => v.Id)
                .Take(remaining)
                .ToListAsync();

            if (pending.Count == 0) { Console.WriteLine($"{code}: nothing to enrich."); continue; }
            Console.WriteLine($"{code}: enriching {pending.Count} word(s)…");

            int levelEnriched = 0;
            for (int i = 0; i < pending.Count; i += Batch)
            {
                var chunk = pending.Skip(i).Take(Batch).ToList();
                var inputs = chunk
                    .Select(v => new VocabEnrichInputDto(v.German, v.English, v.PartOfSpeech))
                    .ToList();

                var result = await lang.EnrichVocabularyAsync(code, inputs);
                var byGerman = new Dictionary<string, VocabEnrichItemDto>();
                foreach (var it in result.Items)
                    byGerman[it.German.Trim().ToLowerInvariant()] = it; // last wins on dupes

                int before = levelEnriched;
                foreach (var v in chunk)
                {
                    if (!byGerman.TryGetValue(v.German.Trim().ToLowerInvariant(), out var e)) continue;
                    if (!string.IsNullOrWhiteSpace(e.Note)) v.Note = e.Note.Trim();
                    if (!string.IsNullOrWhiteSpace(e.Example)) v.ExampleSentence = e.Example.Trim();
                    if (!string.IsNullOrWhiteSpace(e.Note) || !string.IsNullOrWhiteSpace(e.Example)) levelEnriched++;
                }
                await db.SaveChangesAsync();

                if (levelEnriched == before)
                {
                    Console.WriteLine("  No enrichment returned — is ANTHROPIC_API_KEY set on the language-service? Stopping.");
                    Console.WriteLine($"Done. Enriched {totalEnriched + levelEnriched} word(s) total.");
                    return;
                }
                Console.WriteLine($"  {code}: +{levelEnriched} (of {pending.Count})");
            }

            totalEnriched += levelEnriched;
            remaining -= levelEnriched;
        }

        Console.WriteLine($"Done. Enriched {totalEnriched} word(s) total.");
    }
}
